permissions:
  contents: read
  deployments: write

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Create GitHub Deployment
    id: create_deployment
    uses: peter-evans/create-deployment@v2
    with:
      token: ${{ secrets.ACCESS_TOKEN }}
      environment: production
      ref: ${{ github.sha }}

  - name: Deploy to Netlify
    uses: nwtgck/actions-netlify@v3
    with:
      publish-dir: .
      production-deploy: true
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  - name: Mark Deployment Successful
    if: success()
    uses: peter-evans/create-deployment-status@v2
    with:
      token: ${{ secrets.ACCESS_TOKEN }}
      deployment-id: ${{ steps.create_deployment.outputs.deployment_id }}
      state: success
      environment: production
